# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

workspace 'iOSLogBrowserSDKDemo.xcworkspace'
project 'iOSLogBrowserSDKDemo.xcodeproj'

target 'iOSLogBrowserSDKDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for iOSLogBrowserSDKDemo
  pod 'XLFacility', git: 'https://github.com/pcjbird/XLFacility.git', :modular_headers => true
  pod 'iOSLogBrowserSDK', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
end
